repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.280
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
      args: [ --assume-in-merge ]
    - id: check-symlinks
    - id: check-toml
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
      args: [ --pytest-test-first ]
    - id: no-commit-to-branch
      args: [ --branch=main, --branch=develop]
    - id: pretty-format-json
      args: [ --autofix, indent 4 ]
    - id: trailing-whitespace

- repo: https://github.com/best-doctor/pre-commit-hooks
  rev: v1.0.4
  hooks:
  - id: mccabe-complexity
    name: Check functions complexity
    language: python
